urls:
  api: 'https://devnet-api.multiversx.com'
  redis: '127.0.0.1'
contracts:
  aggregator: 'erd1qqqqqqqqqqqqqpgqttja5hhug9rw0umu25ptq3reqmqrc4rll3tsqtvm0n'
features:
  cacheWarmer:
    enabled: true
    port: 5201
  privateApi:
    enabled: false
    port: 4000
